title:             Picroup
email:             picourp@gmail.com
description:       官方博客
author:            Picroup
baseurl:           ""
url:               "https://blog.picroup.com"

# Social Profiles
// twitter_username:  SBootstrap
github_username:   Picroup
// facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

sass:
  style: compressed
future: true
